version: "3.9"
services: 
  deepface: 
    build: deepface/.
    ports: 
      - "8000:5000" 
    volumes: 
      - ./deepface:/deepface
    command: python /deepface/api.py
  react: 
    build: react/.
    ports: 
      - "3000:3000" 
    volumes: 
      - ./react:/app
    command: ["sh", "entrypoint.sh"]
